name: Golang Security

on:
  push:
    branches:
      - master
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  gosec:
    name: Gosec Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: golang-security-action
        uses: Ynniss/golang-security-action@v0.1.3
        with:
          args: '-no-fail'
          CODE_PATH: .
