name: Publish Image
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

  # wait for Golang tests
  workflow_run:
    workflows: ["Golang"]
    types:
      - completed

jobs:
  build:
    # do not build and push if tests failed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build & Push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Push
        uses: docker/build-push-action@v1
        with:
          path: .
          registry: quay.io
          username: ${{ secrets.QUAY_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}
          repository: invoca/tenable-scan-launcher
          tag_with_sha: true
          tag_with_ref: true
          add_git_labels: true
